export const allTransactions = [
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: null, deposited: 3438.29, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Opening Balance', withdrawn: null, deposited: null, balance: 3451.71 },
  { date: 'Jun 23', description: 'Point of sale purchase\nApos Westside Charli St. John\'S NLCA', withdrawn: 13.42, deposited: null, balance: 3438.29 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
  { date: 'Jun 24', description: 'Point of sale purchase\nFpos Starbucks Coffee #22St. John\'\'Snlcd', withdrawn: 9.86, deposited: null, balance: 3428.43 },
];